name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install root dependencies 🔧
        run: npm install

      - name: Build library 🏗️
        run: npm run build

      - name: Install example-app dependencies 🔧
        run: npm install
        working-directory: exe/example-app

      - name: Install example-app-e2e dependencies 🔧
        run: npm install
        working-directory: exe/example-app-e2e

      - name: Install Playwright Browsers 🌐
        run: npx playwright install --with-deps chromium
        working-directory: exe/example-app-e2e

      - name: Run E2E tests 🧪
        run: npm run test:e2e
        working-directory: exe/example-app-e2e

      - name: Build example-app 🏗️
        run: npm run build
        working-directory: exe/example-app
        env:
          VITE_BASE: /tea-cup-form/

      - name: Upload artifact 📤
        uses: actions/upload-pages-artifact@v3
        with:
          path: exe/example-app/dist

      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
